"""Legacy compatibility shim for auth access.

New runtime code should import from ``crate.db.repositories.auth``.
This module remains only to keep the deprecated compat surface and older
tests/scripts working while the backend migration finishes.
"""

from crate.db.tx import transaction_scope
from crate.db.repositories.auth import (
    _seed_admin,
    cleanup_ended_jam_rooms,
    cleanup_expired_sessions,
    consume_auth_invite,
    count_users,
    create_auth_invite,
    create_session,
    create_user,
    delete_session,
    delete_user,
    get_auth_invite,
    get_session,
    get_user_by_email,
    get_user_by_external_identity,
    get_user_by_google_id,
    get_user_by_id,
    get_user_external_identity,
    get_user_presence,
    get_users_presence,
    list_auth_invites,
    list_sessions,
    list_user_external_identities,
    list_users,
    list_users_map_rows,
    revoke_other_sessions,
    revoke_session,
    suggest_username,
    touch_session,
    unlink_user_external_identity,
    update_user,
    update_user_last_login,
    upsert_user_external_identity,
)

__all__ = [
    "_seed_admin",
    "cleanup_ended_jam_rooms",
    "cleanup_expired_sessions",
    "consume_auth_invite",
    "count_users",
    "create_auth_invite",
    "create_session",
    "create_user",
    "delete_session",
    "delete_user",
    "get_auth_invite",
    "get_session",
    "get_user_by_email",
    "get_user_by_external_identity",
    "get_user_by_google_id",
    "get_user_by_id",
    "get_user_external_identity",
    "get_user_presence",
    "get_users_presence",
    "list_auth_invites",
    "list_sessions",
    "list_user_external_identities",
    "list_users",
    "list_users_map_rows",
    "revoke_other_sessions",
    "revoke_session",
    "suggest_username",
    "touch_session",
    "transaction_scope",
    "unlink_user_external_identity",
    "update_user",
    "update_user_last_login",
    "upsert_user_external_identity",
]
