"""Legacy compatibility shim for library access.

New runtime code should import from ``crate.db.repositories.library`` for
simple CRUD/lookups or from dedicated ``queries`` / ``jobs`` modules for
specialized SQL. This module remains only to keep the frozen compat facade
and older tests/scripts working while the backend migration finishes.
"""

from crate.db.repositories.library import (
    delete_album,
    delete_artist,
    delete_quarantined_album,
    delete_track,
    enrich_track_refs,
    find_user_playlist_by_name,
    get_album_quality_map,
    get_albums_missing_covers,
    get_artist_analysis_tracks,
    get_artist_refs_by_names,
    get_artist_tracks_for_setlist,
    get_library_album,
    get_library_album_by_id,
    get_library_albums,
    get_library_artist,
    get_library_artist_by_id,
    get_library_artists,
    get_library_stats,
    get_library_track_by_id,
    get_library_track_by_path,
    get_library_track_by_storage_id,
    get_library_track_count,
    get_library_tracks,
    get_library_tracks_by_storage_ids,
    get_release_by_id,
    get_track_path_by_id,
    get_track_rating,
    quarantine_album,
    set_track_rating,
    unquarantine_album,
    update_artist_enrichment,
    update_artist_has_photo,
    update_track_analysis,
    upsert_album,
    upsert_artist,
    upsert_track,
)

__all__ = [
    "delete_album",
    "delete_artist",
    "delete_quarantined_album",
    "delete_track",
    "enrich_track_refs",
    "find_user_playlist_by_name",
    "get_album_quality_map",
    "get_albums_missing_covers",
    "get_artist_analysis_tracks",
    "get_artist_refs_by_names",
    "get_artist_tracks_for_setlist",
    "get_library_album",
    "get_library_album_by_id",
    "get_library_albums",
    "get_library_artist",
    "get_library_artist_by_id",
    "get_library_artists",
    "get_library_stats",
    "get_library_track_by_id",
    "get_library_track_by_path",
    "get_library_track_by_storage_id",
    "get_library_track_count",
    "get_library_tracks",
    "get_library_tracks_by_storage_ids",
    "get_release_by_id",
    "get_track_path_by_id",
    "get_track_rating",
    "quarantine_album",
    "set_track_rating",
    "unquarantine_album",
    "update_artist_enrichment",
    "update_artist_has_photo",
    "update_track_analysis",
    "upsert_album",
    "upsert_artist",
    "upsert_track",
]
