import logging

from crate.db.queries.analytics_artist import (
    get_artist_albums_timeline,
    get_artist_audio_by_album,
    get_artist_format_distribution,
    get_artist_genre_tags,
    get_artist_top_tracks,
)
from crate.db.queries.analytics_audio_insights import (
    get_insights_acoustic_instrumental,
    get_insights_bpm_distribution,
    get_insights_energy_danceability,
    get_insights_feature_coverage,
    get_insights_bitrate_distribution,
    get_insights_key_distribution,
    get_insights_loudness_distribution,
    get_insights_mood_distribution,
)
from crate.db.queries.analytics_catalog_insights import (
    get_insights_albums_by_year,
    get_insights_artist_depth,
    get_insights_countries,
    get_insights_format_distribution,
    get_insights_popularity,
    get_insights_top_albums,
    get_insights_top_genres,
)
from crate.db.queries.analytics_overview import (
    get_avg_tracks_per_album,
    get_bitrate_distribution,
    get_decade_distribution,
    get_format_distribution,
    get_genre_distribution,
    get_overview_stat_summary,
    get_sizes_by_format_gb,
    get_stats_analyzed_track_count,
    get_stats_avg_album_duration_min,
    get_stats_avg_bitrate,
    get_stats_duration_hours,
    get_stats_recent_albums,
    get_stats_top_genres,
    get_timeline_albums,
    get_top_artists_by_albums,
    get_total_duration_hours,
)

log = logging.getLogger(__name__)

__all__ = [
    "get_artist_albums_timeline",
    "get_artist_audio_by_album",
    "get_artist_format_distribution",
    "get_artist_genre_tags",
    "get_artist_top_tracks",
    "get_avg_tracks_per_album",
    "get_bitrate_distribution",
    "get_decade_distribution",
    "get_format_distribution",
    "get_genre_distribution",
    "get_insights_acoustic_instrumental",
    "get_insights_albums_by_year",
    "get_insights_artist_depth",
    "get_insights_bitrate_distribution",
    "get_insights_bpm_distribution",
    "get_insights_countries",
    "get_insights_energy_danceability",
    "get_insights_feature_coverage",
    "get_insights_format_distribution",
    "get_insights_key_distribution",
    "get_insights_loudness_distribution",
    "get_insights_mood_distribution",
    "get_insights_popularity",
    "get_insights_top_albums",
    "get_insights_top_genres",
    "get_overview_stat_summary",
    "get_sizes_by_format_gb",
    "get_stats_analyzed_track_count",
    "get_stats_avg_album_duration_min",
    "get_stats_avg_bitrate",
    "get_stats_duration_hours",
    "get_stats_recent_albums",
    "get_stats_top_genres",
    "get_timeline_albums",
    "get_top_artists_by_albums",
    "get_total_duration_hours",
]
